### GET posts/:id
GET http://localhost:4000/api/todos/5f483d67e352b825b8d90d6e

### GET posts
GET http://localhost:4000/api/todos

### POST Creating a new post
POST http://localhost:4000/api/todos
Content-Type: application/json

{
  "name": "Emprendedores",
  "description": "Tengo algo pendiente",
  "status": false,
}

### PUT Update post

PUT http://localhost:4000/api/todos/5f483d67e352b825b8d90d6e
Content-Type: application/json

{
  "name": "Electrónica Digital",
  "description": "Tengo una reunion",
  "status": false,
}

### DELETE Delete post
DELETE http://localhost:4000/api/todos/5f483d67e352b825b8d90d6e